---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:557690580165:task-definition/project6-task:1"
        LoadBalancerInfo:
          ContainerName: "hruthincontainer"
          ContainerPort: 8080
