---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:557690580165:task-definition/myspringtask:3"
        LoadBalancerInfo:
          ContainerName: "springhruthin"
          ContainerPort: 8080
